version: '3.8'

services:
  web_app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: web-app
    ports:
      - "8081:80"
    volumes:
      - ./app.py:/app/main.py
    environment:
      - DB_HOST=db-postgres
      - POSTGRES_PASSWORD=pass
    networks:
      - flash-sale-net

  database:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: pass
    networks:
      - flash-sale-net

  # --- ADD THIS SERVICE ---
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - flash-sale-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - flash-sale-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - flash-sale-net

networks:
  flash-sale-net:
    driver: bridge

